/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package celiserver.ui;

import celiserver.model.Device;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;

/**
 *
 * @author Gerry
 */
public class MainFrame extends javax.swing.JFrame {

    /** The device behind this control. */
    private final Device device;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this(null);
    }
    
    public MainFrame(Device device) {
        initComponents();
        this.device = device;
        
        ActionListener colorModeListener = (ActionEvent ae) -> {
            AbstractButton radio = (AbstractButton) ae.getSource();
            device.performAction("1" + radio.getActionCommand());
        };
        
        ActionListener dayTimeListener = (ActionEvent ae) -> {
            AbstractButton radio = (AbstractButton) ae.getSource();
            device.performAction("2" + radio.getActionCommand());
        };
        
        btnColorMode_redToGreen.addActionListener(colorModeListener);
        btnColorMode_greenToRed.addActionListener(colorModeListener);
        
        btnDayTime_morning.addActionListener(dayTimeListener);
        btnDayTime_forenoon.addActionListener(dayTimeListener);
        btnDayTime_noon.addActionListener(dayTimeListener);
        btnDayTime_afternoon.addActionListener(dayTimeListener);
        btnDayTime_evening.addActionListener(dayTimeListener);
        btnDayTime_night.addActionListener(dayTimeListener);
        
        btnNewDay.addActionListener((ae) -> {
            device.performAction("3~");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupColorMode = new javax.swing.ButtonGroup();
        btnGroupDayTime = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnColorMode_redToGreen = new javax.swing.JRadioButton();
        btnColorMode_greenToRed = new javax.swing.JRadioButton();
        btnDayTime_morning = new javax.swing.JRadioButton();
        btnDayTime_forenoon = new javax.swing.JRadioButton();
        btnDayTime_noon = new javax.swing.JRadioButton();
        btnDayTime_afternoon = new javax.swing.JRadioButton();
        btnDayTime_evening = new javax.swing.JRadioButton();
        btnDayTime_night = new javax.swing.JRadioButton();
        btnNewDay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ColorMode:");

        jLabel2.setText("DayTime:");

        btnGroupColorMode.add(btnColorMode_redToGreen);
        btnColorMode_redToGreen.setText("Red to Green");
        btnColorMode_redToGreen.setActionCommand("0");

        btnGroupColorMode.add(btnColorMode_greenToRed);
        btnColorMode_greenToRed.setText("Green to Red");
        btnColorMode_greenToRed.setActionCommand("1");

        btnGroupDayTime.add(btnDayTime_morning);
        btnDayTime_morning.setText("Morning");
        btnDayTime_morning.setActionCommand("0");

        btnGroupDayTime.add(btnDayTime_forenoon);
        btnDayTime_forenoon.setText("Forenoon");
        btnDayTime_forenoon.setActionCommand("1");

        btnGroupDayTime.add(btnDayTime_noon);
        btnDayTime_noon.setText("Noon");
        btnDayTime_noon.setActionCommand("2");

        btnGroupDayTime.add(btnDayTime_afternoon);
        btnDayTime_afternoon.setText("Afternoon");
        btnDayTime_afternoon.setActionCommand("3");

        btnGroupDayTime.add(btnDayTime_evening);
        btnDayTime_evening.setText("Evening");
        btnDayTime_evening.setActionCommand("4");

        btnGroupDayTime.add(btnDayTime_night);
        btnDayTime_night.setText("Night");
        btnDayTime_night.setActionCommand("5");

        btnNewDay.setText("Reset Entries");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnColorMode_redToGreen)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnDayTime_evening)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDayTime_morning)
                                            .addComponent(btnDayTime_noon))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnDayTime_night, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDayTime_afternoon)
                                            .addComponent(btnDayTime_forenoon)))
                                    .addComponent(btnColorMode_greenToRed))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorMode_redToGreen)
                    .addComponent(btnColorMode_greenToRed))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDayTime_morning)
                    .addComponent(btnDayTime_forenoon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDayTime_noon)
                    .addComponent(btnDayTime_afternoon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDayTime_evening)
                    .addComponent(btnDayTime_night))
                .addGap(18, 18, 18)
                .addComponent(btnNewDay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.device != null) {
            this.device.handleMessage("disconnect");
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnColorMode_greenToRed;
    private javax.swing.JRadioButton btnColorMode_redToGreen;
    private javax.swing.JRadioButton btnDayTime_afternoon;
    private javax.swing.JRadioButton btnDayTime_evening;
    private javax.swing.JRadioButton btnDayTime_forenoon;
    private javax.swing.JRadioButton btnDayTime_morning;
    private javax.swing.JRadioButton btnDayTime_night;
    private javax.swing.JRadioButton btnDayTime_noon;
    private javax.swing.ButtonGroup btnGroupColorMode;
    private javax.swing.ButtonGroup btnGroupDayTime;
    private javax.swing.JButton btnNewDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
